name: florafi
description: Florafy client library
version: 0.1.0
homepage: https://github.com/cafe01/florafi-dart

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  mqtt_client: ^9.6.5
  logging: ^1.0.2
  http: ^0.13.4

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  async: ^2.8.2
  yaml: ^3.1.0
  args: ^2.3.0
  path: ^1.8.1
  dart_style: ^2.2.2
